### ISSUE TITLE
question on prices and xmrig

### ISSUE THREAD

**Issue by gabrielseibel1** [MoneroOcean/meta-miner#49]
hello. does the algorithm consider the current prices for the coins mined, and chooses the most profitable one? also, how does it differ from https://github.com/MoneroOcean/xmrig in this regard?

thanks

**Comment by Spudz76** [comment]
Normal xmrig doesn't track prices at all, it just mines what you told it to, and does not algo-switch.

MoneroOcean gets prices from TradeOgre since that's where it does the swapping from altcoins (to BTC for milliseconds) to XMR.  The current adjusted hashrate multiplier is listed on the `COINS` page as a percent (divide by 100).

The most profitable one would be your hashrates (the `algo-perf` list sent once at login) times these multipliers, and whichever one would output more once they are all calculated to a comparable hashrate (rx/0 equivalent).  Because hashrates across algorithms do not compare directly.

For instance right now I am mining 120MH/s autolykos2 which is paying 30KH/s rx/0.  Currently that is `0.02744%` on the coins page, so 120000KH/s * 0.0002744 = 32.928KH/s so the 30KH/s displayed is about right (fluctuation due to price continually changing, and luck).

All these calculations occur on the server side, based completely on what `algo-perf` was sent, which could be inaccurate or complete lies, it will just send algos you claimed to have a high equivalent hashrate with.

**Comment by gabrielseibel1** [comment]
Thanks a lot for the explanation
